version: '3.7'

services:
    resume:
        image: ubuntu:18.04
        container_name: Resume
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/home
        labels:
            NAME: 'Resume'