name: Auto assign PR author
on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
jobs:
  add-author:
    runs-on: ubuntu-latest
    steps:
      - name: Add PR author as assignee
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const author = context.payload.pull_request.user.login;
            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              assignees: [author]
            });

