name: Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.12.1
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Install dependencies
        # Use --no-frozen-lockfile so that CI doesn't fail when pnpm-lock.yaml
        # is slightly out of sync with package.json
        run: pnpm install --no-frozen-lockfile
      - name: Run linter
        run: pnpm lint
