name: Label PRs

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Run Labeler
        uses: actions/labeler@v5.0.0
        with:
          repo-token: ${{ secrets.PAT }}

      - name: Debug Output
        run: |
          pwd
          ls -la
